### ISSUE TITLE
Decrease highlight bg color compared to selection bg color

### ISSUE THREAD

**Issue by jsejcksn** [hedinne/popping-and-locking-vscode#11]
Example to illustrate:

![vscode-theme-popping-and-locking-highlight](https://user-images.githubusercontent.com/868251/85185563-0641d580-b25a-11ea-8b2b-122ed2e3375b.png)
The cursor is next to a string token so it's highlighted (not selected).

![vscode-theme-popping-and-locking-selection](https://user-images.githubusercontent.com/868251/85185589-27a2c180-b25a-11ea-8d8a-a66dccf8e751.png)
The string is selected.

It is very difficult to know the difference without looking at the status bar in the bottom right.

I think the token highlight should have a more subtle bg color and the selected text should have a stronger bg color.

**Comment by jsejcksn** [comment]
@hedinne Thoughts?

**Comment by hedinne** [comment]
Hi and sorry for the late reply. You are totally right. The not selected state should not get this much attention and defiantly shouldn't be mistaken for the selected state.

I think this ended like this is since there are so many selected word states in VS Code. At the top of my mind there are theses two, "same keyword as the one that is selected", "matches the tag that is selected (i.e. HTML)" and "selected sub-string within a highlighted word". I tried my best to make them different from each other but I clearly didn't catch all cases. And the colors and contrast in the highlights could be better.

I've already started a rewrite of the theme to fix a lot of minor problems I've noticed but it has taken way longer then I expected since I've been really busy with work and a new baby.

**Comment by jsejcksn** [comment]
I’m glad you agree. This theme is one of the small minority that differentiates a maximum amount of tokens in different contexts. (And the colors are ✨.) It’s hard to imagine finding something else to use!

**Comment by jsejcksn** [comment]
Hi @hedinne. Just checking in to see how things are going. Are you in need of any specific help with the rewrite?

**Comment by hedinne** [comment]
Hey hey, I just fixed this and will publish it tomorrow. Sorry how long it took.

**Comment by jsejcksn** [comment]
No worries. I'm just glad that you still care about this project and found time for it! Lots of eyes and minds will be even happier.

**Comment by jsejcksn** [comment]
I see a change related to this in https://github.com/hedinne/popping-and-locking-vscode/commit/29a27e1cb62e077dc920dbb6f1f7aaedeb9a06f8. I'm guessing it will be available next time you bump the version number in `package.json`?

**Comment by jsejcksn** [comment]
> I think this ended like this is since there are so many selected word states in VS Code. At the top of my mind there are theses two, "same keyword as the one that is selected", "matches the tag that is selected (i.e. HTML)" and "selected sub-string within a highlighted word". I tried my best to make them different from each other but I clearly didn't catch all cases. And the colors and contrast in the highlights could be better.

Now that I've begun looking at some of these descriptions, I agree with you. 😅 It will take some time to understand their meanings and how they affect the colors during various states.

After digging a little bit further, here is what I've observed.

Currently, this is what highlighted text looks like vs selected text:

_highlighted (I have only clicked once on line 60)_
<img width="609" alt="current-highlight" src="https://user-images.githubusercontent.com/868251/132161136-44ffbbb2-5cdf-491e-8eee-5c595def26f0.png">

_selected (I have selected the word "selection" on line 60)_
<img width="609" alt="current-selection" src="https://user-images.githubusercontent.com/868251/132161221-dce48b64-d5f1-41c7-8843-528347afc10f.png">

To me, this contrast seems inverted, because the highlighted bg color is stronger than the selection bg color. By swapping the values, it results in what I think is a more natural balance:

_highlighted (I have only clicked once on line 62)_
<img width="609" alt="proposed-highlight" src="https://user-images.githubusercontent.com/868251/132161441-998b26f5-0a20-406b-abe2-8357ade70253.png">

_selected (I have selected the word "selection" on line 62)_
<img width="609" alt="proposed-selection" src="https://user-images.githubusercontent.com/868251/132161456-b3c89583-e9e7-41e3-b1ef-f48d2bbc1188.png">

Do you agree with this?

**Comment by hedinne** [comment]
I totally agree this looks reverted, and also, it is tough to know what the color change is representing.

It is a bit tricky to do right. I have looked at few other themes, and most of them struggle with this. The problem is that few different states have to be represented, and some of them can be active simultaneously. So, for example, there is "selected text," "text Is not selected but on an active block," "the active block is the initialization of the variable" (or something like that), "same string as the selected block," and more.

So my suggestion is that the selected text gets a more saturated background color:
![image](https://user-images.githubusercontent.com/7573694/132261169-fa6be5c0-73c0-4173-8872-2523b48b0417.png)

Active block but not selected gets a darker background. It is barely visible, but I think that is fine since I don't see much value in this state. (Note: the import is also darker).
![image](https://user-images.githubusercontent.com/7573694/132261259-1ce9c195-6926-4c60-9133-e1a512df58c6.png)

The combination of these states looks like this.
![image](https://user-images.githubusercontent.com/7573694/132261300-80ec5258-42bf-4521-a7a6-1fd083b2d681.png)

And the rest is untouched. E.g., Matches the same string as the active block.
![image](https://user-images.githubusercontent.com/7573694/132261364-a23b743f-7b67-47fd-af31-58a7d00b65aa.png)


What do you think?

**Comment by jsejcksn** [comment]
I'm not sure that I understand exactly, but maybe you can help by answering a question:

I see that you recently made [a commit with the title "selected text color"](https://github.com/hedinne/popping-and-locking-vscode/commit/acd6ed8b635fc4ca71e2e09b8e131c07492080dd) which increases the version to `2.0.9`. I also see that on [the extension's marketplace page](https://marketplace.visualstudio.com/items?itemName=hedinne.popping-and-locking-vscode), the current version is `2.0.10`. However, I don't see any references to that version in this repository. Is the code that was uploaded to the marketplace as v`2.0.10` the same code in the commit linked above? And are the styles in that commit the same styles used in the example screenshots in [your comment](https://github.com/hedinne/popping-and-locking-vscode/issues/11#issuecomment-913860246)?

**Comment by hedinne** [comment]
Last night I made more modifications to the highlights and screenshots of them here above. I decided to wait for few hours and see you had any comments. Then late last night I published the changes to the marketplace but forgot to push them to Github. The reason the versions don't add up is that I changed the version in package.json and then used the publishing commend that auto-increments the version. So there isn't any version `2.0.9`.

I'm not perfectly happy with the changes. I think the saturated color is a bit off but I don't know of a better way to convey this state.

**Comment by jsejcksn** [comment]
Thanks for explaining! I'm happy to give feedback, although it may not always be as quick as you'd like.

My interpretation of what you said is that the source code in the commit I referenced and the published extension v`2.0.10` are identical except for the version number. Is that right?

> I'm not perfectly happy with the changes. I think the saturated color is a bit off but I don't know of a better way to convey this state.

I have been thinking about this also. Two thoughts:

- Perhaps the introduction of a new color would be useful here. What do you think about a color in the violet/lavender/purple space?

- You might be on to something using not just lighter tones for background colors, but also darker tones. Obviously, the usable range is smaller with darker tones because the base background is already dark, but perhaps it's possible to explore further in that area.
